name: Yellowlab Tools

on:
  deployment_status

jobs:
  yellow-lab-tools-check:
    name: Detect performance and front-end issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcuslindblom/yellow-lab-tools
      - uses: marcuslindblom/yellow-lab-tools@main
        with:
          url: ${{ secrets.SECURITY_HEADERS_URL }}
          score: 100
          host: https://yellowlab.tools/api/runs
