on: [push]

name: mabl

jobs:
    test:
        name: mabl Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get branch name (merge)
              if: github.event_name != 'pull_request'
              shell: bash
              run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

            - name: Get branch name (pull request)
              if: github.event_name == 'pull_request'
              shell: bash
              run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

            - name: Debug
              run: echo ${{ env.BRANCH_NAME }}
            - name: Functional test deployment
              id: mabl-test-deployment
            - uses: nelonoel/branch-name@v1
            - run: echo aris ${BRANCH_NAME}
              uses: mablhq/github-run-tests-action@v1
              env:
                  #          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
                  MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  application-id: zCkW6Mhrybz0kvGKVt0VLA-a
                  environment-id: HOg8AuD5iItWh6uOFnzQXg-e
#          uri:
